
from selenium.webdriver.common.by import By
import time

def home(driver):
    time.sleep(3)
    driver.find_element(By.ID, "expand-tab").click()
    time.sleep(2)
    driver.find_element(By.ID, "expand-tab").click()
    time.sleep(4)
    driver.find_element(By.ID, "expand-tab").click()
    time.sleep(2)

    driver.execute_script("window.scrollBy(0, 230);")
    time.sleep(2)

    driver.find_element(By.ID, "showweek").click()
    time.sleep(3)
    driver.find_element(By.ID, "showmonth").click()
    time.sleep(3)
    driver.find_element(By.ID, "showyear").click()
    time.sleep(7)
    driver.execute_script("window.scrollBy(0, 480);")
    time.sleep(4)

    driver.find_element(By.XPATH, "/html/body/div[4]/div[8]/div[1]/div/div[1]/div[1]/div[2]/div/div[2]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/div[4]/div[8]/div[1]/div/div[1]/div[1]/div[2]/div/div[1]").click()
    time.sleep(2)
    driver.find_element(By.ID, "show-booking-week").click()
    time.sleep(3)
    driver.find_element(By.ID, "show-booking-month").click()
    time.sleep(3)
    driver.find_element(By.ID, "show-booking-year").click()
    time.sleep(3)
    driver.find_element("css selector", "i.bi.bi-arrows-angle-expand").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/div[4]/div[2]/div/div/div[1]/div[1]/div[2]/div/div[2]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/div[4]/div[2]/div/div/div[1]/div[1]/div[2]/div/div[1]").click()
    time.sleep(2)
    driver.find_element(By.ID, "show-booking-week").click()
    time.sleep(3)
    driver.find_element(By.ID, "show-booking-month").click()
    time.sleep(3)
    driver.find_element(By.ID, "show-booking-year").click()
    time.sleep(3)
    # Find the button element and click it
    driver.find_element("css selector", "button.lead-head-btn.text-primary.bg-white").click()
    time.sleep(2)
    driver.find_element("css selector", "i.bi.bi-arrows-angle-contract").click()
    time.sleep(2)

    driver.find_element(By.XPATH, "/html/body/div[4]/div[8]/div[3]/div/div[1]/div[1]/div[2]/div[2]/div[2]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/div[4]/div[8]/div[3]/div/div[1]/div[1]/div[2]/div[2]/div[1]").click()
    time.sleep(2)

    driver.find_element("id", "user-dashboard-check").click()
    time.sleep(2)
    driver.find_element(By.ID, "show-user-week").click()
    time.sleep(3)
    driver.find_element(By.ID, "show-user-month").click()
    time.sleep(3)
    driver.find_element(By.ID, "show-user-year").click()
    time.sleep(3)
    driver.find_element(By.ID, "show-user-next-page").click()
    time.sleep(4)

    # Locate the element by its ID and click it
    driver.find_element(By.XPATH, "/html/body/div[4]/div[2]/div/div/div[1]/div[1]/div[2]/div[2]/div[2]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/div[4]/div[2]/div/div/div[1]/div[1]/div[2]/div[2]/div[1]").click()
    time.sleep(2)
    driver.find_element(By.XPATH, "/html/body/div[4]/div[2]/div/div/div[1]/div[1]/div[2]/button[1]").click()
    time.sleep(3)
    driver.find_element(By.XPATH, "/html/body/div[4]/div[2]/div/div/div[1]/div[1]/div[2]/button[2]").click()
    time.sleep(3)
    driver.find_element(By.XPATH, "/html/body/div[4]/div[2]/div/div/div[1]/div[1]/div[2]/button[3]").click()
    time.sleep(3)
    # Find the button element and click it
    driver.find_element("css selector", "button.lead-head-btn.text-primary.bg-white").click()
    time.sleep(2)
    driver.find_element("css selector", "i.bi.bi-arrows-angle-contract").click()

    time.sleep(5)
    driver.execute_script("window.scrollBy(0, 630);")
    time.sleep(4)
    driver.execute_script("window.scrollBy(0, 880);")
    time.sleep(4)
    driver.find_element(By.ID, "show-wordcloud-next-page").click()
    time.sleep(6)
    driver.find_element("css selector", "button.lead-head-btn.text-primary.bg-white").click()
    time.sleep(2)
    driver.find_element("css selector", "i.bi.bi-arrows-angle-contract").click()
    time.sleep(2)
    driver.execute_script("window.scrollBy(0, 1760);")
    time.sleep(4)
    driver.find_element(By.ID, "show-map-next-page").click()
    time.sleep(6)
    driver.find_element(By.CSS_SELECTOR, "button.lead-head-btn.text-primary.bg-white").click()
    time.sleep(2)
    driver.find_element("css selector", "i.bi.bi-arrows-angle-contract").click()
    time.sleep(3)

